test: test.cpp Indexer.cpp Searcher.cpp 
	 g++ -o tool \
		 -I/usr/include/ -I/usr/include/CLucene -I/usr/include/recommend \
	 	 test.cpp Indexer.cpp Searcher.cpp \
         -lclucene-core -lrecommend -lpthread -lm
